name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: GPP='g++ --std=c++14' make all
    - name: sample test
      run: ./sample -d
    - name: basic_tests
      run: ./basic_tests -d
    - name: benchmark
      run: ./benchmark -d
